package com.housekeeping.entity.enums;

public enum FurnitureType {
    WALL, FLOOR,
    DESK, BED, SOFA, CLOSET, DRAWER, BOOKSHELF, CHAIR, POKEMON, TRASHCAN, DECORATION, LIGHT,
    REFRIGERATOR, WASHINGMACHINE, SINK, OVEN, LIVINGETC,
    TOILET, BATH, TOILETETC
}
